use_frameworks!

platform :ios, '8.0'
#source 'https://github.com/CocoaPods/Specs.git'
target 'ZSXTestLib_Example' do
  pod 'ZSXTestLib', :path => '../'

  target 'ZSXTestLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
